/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ozlympicsgame;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author anu
 */
public class SelectAGame extends javax.swing.JFrame {
public static List<Person> players=new ArrayList<Person>();
    /**
     * Creates new form MainClass
     */
    public SelectAGame() {
        initComponents();
        selectGame();
        connect();
    }
final String JDBC_DRIVER = "org.apache.derby.jdbc.ClientDriver";
  final String DB_URL = "jdbc:derby://localhost:1527/player;create=true";
  final String USER="player";
  final String PASS="player";
   Connection conn=null;
   public void connect(){
        try{
         
     Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
      conn = DriverManager.getConnection(DB_URL,USER,PASS);
         if(conn!=null){
             String sql;
               try {
        sql = "select * from player";
 String result1 = null;
Statement statement = conn.createStatement();
ResultSet rs= statement.executeQuery(sql);
if(rs!=null){
    
 while(rs.next()){
     Person pp=new Person(rs.getString(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getInt(6),rs.getInt(7));
     players.add(pp);
     System.out.println(pp);
 }
}else{
    
}
               } catch(Exception e){
                   e.printStackTrace();
               }

         }else{
             writePlayers();
         }
        randomWinner();
      }catch(Exception e){
          e.printStackTrace();
          writePlayers();
           randomWinner();
      }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectGameLable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectGameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectGameLable.setText("Please select a game to play...");
        selectGameLable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Display the Final result of all game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Display the Points of all Athletes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(100, 100, 100))))
                    .addComponent(selectGameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(selectGameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
int currentGame;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      FinalResults fr=new FinalResults();
      fr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
         jList1.addListSelectionListener(new ListSelectionListener() {

           @Override
           public void valueChanged(ListSelectionEvent e) {
              //To change body of generated methods, choose Tools | Templates.
               int itemid=jList1.getSelectedIndex();
     
               if(itemid == 0){
                   RunningGame run=new RunningGame();
                   run.setVisible(true);
               }else if(itemid==1){
                  Swimming sm=new Swimming();
                   sm.setVisible(true);
               }else{
                  
                     CyclingGame cc=new CyclingGame();
                   cc.setVisible(true);
                   
               }
           }
       });
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AllUserPoints all=new AllUserPoints();
        all.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see (http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectAGame().setVisible(true);
            }
        });
    }
    public void selectGame(){
      
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Running", "Swimming", "Cycling"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);
    }
       
public void writePlayers(){
    
   Person at = new Person("R01", "Anthony", 28, "Victoria","runner",5,10);
		Person at1 = new Person("R02", "Kundan", 34, "Western Australia","runner",5,0);
		Person at2 = new Person("R03", "Pooja", 24, "Western Australia","runner",5,0);
		Person at3 = new Person("R04", "Domenic", 25, "Western Australia","runner",10,10);
		Person at4 = new Person("R05", "Alisha", 33, "Western Australia","runner",4,0);
		Person at5 = new Person("R06", "Gurleen", 29, "Western Australia","runner",4,0);
		Person at6 = new Person("R07", "Chris", 32, "Western Australia","runner",4,0);
		Person at7 = new Person("R08", "Carol", 28, "Western Australia","runner",4,0);
		Person at8 = new Person("R09", "Vaishali", 24, "Western Australia","runner",4,0);
		Person at9 = new Person("R10", "Kim", 23, "Western Australia","runner",4,0);
		Person at10 = new Person("S01", "John", 39, "Queensland","Swimmer",4,0);
		Person at11 = new Person("S02", "Jan", 28, "Queensland","Swimmer",4,0);
		Person at12 = new Person("S03", "Purwa", 31, "Tasmania","Swimmer",4,0);
		Person at13 = new Person("S04", "Jackson", 32, "Tasmania","Swimmer",4,0);
		Person at14 = new Person("S05", "Pushakar", 29, "Tasmania","Swimmer",4,0);
		Person at15 = new Person("S06", "Akshata", 38, "Tasmania","Swimmer",4,0);
		Person at16 = new Person("S07", "Emma", 25, "Tasmania","Swimmer",4,0);
		Person at17 = new Person("S08", "Olivia", 23, "Tasmania","Swimmer",4,0);
		Person at18 = new Person("S09", "Lucas", 34, "Tasmania","Swimmer",4,0);
		Person at19 = new Person("S10", "Eashan", 30, "Tasmania","Swimmer",4,0);
		Person at20 = new Person("C01", "Prajakta", 27, "Victoria","cyclist",4,0);
		Person at21 = new Person("C02", "Nicole", 31, "New South Wales","cyclist",4,0);
		Person at22 = new Person("C03", "Aishwarya", 29, "South Australia","cyclist",4,0);
		Person at23 = new Person("C04", "Shruti", 28, "New South Wales","cyclist",4,0);
		Person at24 = new Person("C05", "Niraj", 23, "New South Wales","cyclist",4,0);
		Person at25 = new Person("C06", "Ava", 38, "New South Wales","cyclist",4,0);
		Person at26 = new Person("C07", "Ashwini", 30, "New South Wales","cyclist",4,0);
		Person at27 = new Person("C08", "Bhagyashri", 24, "New South Wales","cyclist",4,0);
		Person at28 = new Person("C09", "Aiden", 29, "New South Wales","cyclist",4,0);
		Person at29 = new Person("C10", "Liam", 33, "New South Wales","cyclist",4,0);
                players.add(at);
                players.add(at1);
                players.add(at2);
                players.add(at3);
                players.add(at4);
                players.add(at5);
                players.add(at6);
                players.add(at7);
                players.add(at8);
                players.add(at9);
                players.add(at10);
                players.add(at11);
                players.add(at12);
                players.add(at13);
                players.add(at14);
                players.add(at15);
                players.add(at16);
                players.add(at17);
                players.add(at18);
                players.add(at19);
                players.add(at20);
                players.add(at21);
                players.add(at22);
                players.add(at23);
                players.add(at24);
                players.add(at25);
                players.add(at26);
                players.add(at27);
                players.add(at28);
                players.add(at29);
     try {
        String userHomeFolder = System.getProperty("user.home");
File textFile = new File(userHomeFolder, "players.txt");
BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(textFile));
try {
    for(int i=0;i<=players.size()-1;i++){
        Person pt=players.get(i);
         bufferedWriter.newLine();
        bufferedWriter.write(pt.getId()+","+pt.getName()+","+pt.getAge()+","+pt.getState()+","+pt.getTypegame()+","+pt.getFinishtime()+","+pt.getPoints());
        bufferedWriter.newLine();
    }
            bufferedWriter.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
     }catch(Exception e){
         e.printStackTrace();
     }
}
public static List<String>runnerwinner=new ArrayList<>();
public static List<String>swimmer=new ArrayList<>();
public static List<String>cycler=new ArrayList<>();
public static void randomWinner(){
    Random rn = new Random();
    int ans=rn.nextInt(10)+1;
    Person pt = players.get(ans);
    Person pt1=players.get(9+ans);
    Person pt3=players.get(19+ans);
    runnerwinner.add(pt.getName()+","+ans);
   swimmer.add(pt1.getName()+","+ans);
   cycler.add(pt3.getName()+","+ans);
    try {
        String userHomeFolder = System.getProperty("user.home");
File textFile = new File(userHomeFolder, "winner.txt");
BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(textFile));
bufferedWriter.write(runnerwinner.get(0));
bufferedWriter.newLine();
bufferedWriter.write(swimmer.get(0));
bufferedWriter.newLine();
bufferedWriter.write(cycler.get(0));
    }catch(Exception e){
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel selectGameLable;
    // End of variables declaration//GEN-END:variables
}
